
@startuml
' This diagram represents the system context for the IIRA.

skinparam backgroundColor #FEFECE

rectangle "Intra- and Interrater Reliability Analysis (IIRA)" as IIRA #pink {
}

actor User as U
database "Internal Database\n(data/internal_db.csv)" as DB
folder "File System" as FS
cloud "Web Resources" as WR

U --> IIRA : Profile Management\nAnalysis Initiation\nRating Input\nFile Selection
IIRA --> U : GUI Updates\nHelp Content

IIRA --> DB : Profile Data Management

IIRA --> FS : File Import\nFile Export

IIRA --> WR : Web Links

@enduml
